IPv6Network: fix netmask equality check
lukanetconsult/network-address-types pull request #4
Opened 2020-12-11 18:05 UTC by Lctrs

2020-12-15 22:09 UTC, tux-rampage commented
Thank you very much for your contribution. I'll review this later for the failing build. Maybe it's not related to this change.

2020-12-15 22:55 UTC, Lctrs commented
It's not related. The `equals()` methods are not covered by unit tests. Build failures are due to composer v2 being the default on Travis now.

BTW, would you be interested in a migration to Github Actions ? I can work on that.

2020-12-28 21:14 UTC, tux-rampage requested changes
@Lctrs sorry for the delay. I wasn't able to respond sooner.
Would you mind adding a test to cover this?

2020-12-28 23:10 UTC, Lctrs commented
@tux-rampage Done :)

2021-01-05 20:28 UTC, tux-rampage approved these changes
Perfect, thanks 👍🏻

2021-01-05 20:28 UTC, tux-rampage commented on .travis.yml
> +  - infection --min-msi=84 --min-covered-msi=86 --threads=$(nproc) --coverage=coverage
👍🏻

2021-01-08 16:26 UTC, tux-rampage commented
This was merged into `develop`. I just forgot to change the target branch here, so GitHub didn't recognize it.

2021-01-08 16:26 UTC, closed without merging

2021-01-08 16:44 UTC, Lctrs commented
@tux-rampage Thanks !

I saw that you introduced GHA in the project, but it fails at the moment. My invitation to work on it still remains, it will be based on https://github.com/ergebnis/php-library-template.

2021-01-08 17:33 UTC, tux-rampage commented
Thanks, feel free to open a PR to complete GitHub actions. The one right here seem to come from Travis after I enabledthis feature.